server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    max-threads: 200
    min-spare-threads: 10

spring:
  profiles:
    active: prod
  
  datasource:
    url: jdbc:mysql://localhost:3306/techdaily?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: TechDaily2024!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
    open-in-view: false

  thymeleaf:
    cache: true
    mode: HTML
    encoding: UTF-8

  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss

  task:
    execution:
      pool:
        core-size: 5
        max-size: 20
        queue-capacity: 100
    scheduling:
      pool:
        size: 5

logging:
  level:
    root: INFO
    com.spideman: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /var/log/techdaily/application.log
    max-size: 100MB
    max-history: 30

# 应用配置
app:
  name: TechDaily
  version: 1.0.0
  description: 每日技术精选门户

# 爬虫配置
crawler:
  enabled: true
  schedule:
    quick-crawl: "0 0 */6 * * ?" # 每6小时执行一次快速爬取
    full-crawl: "0 0 2 * * ?" # 每天凌晨2点执行完整爬取
  timeout: 30000
  retry-count: 3
  user-agent: "TechDaily-Bot/1.0"

# AI服务配置 (如果需要)
ai:
  enabled: false
  alibaba:
    api-key: ${ALIBABA_AI_API_KEY:}
    model: qwen-plus

# 管理配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized 