server:
  port: 8080

spring:
  application:
    name: tech-daily-backend
  
  # 允许循环引用
  main:
    allow-circular-references: true
  
  # 数据库配置（使用MySQL）
  datasource:
    url: jdbc:mysql://47.237.80.97:3306/techdaily?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: techdaily
    password: TechDaily2025!
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: Asia/Shanghai
  
  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

# 日志配置
logging:
  level:
    com.spideman: INFO
    org.springframework: INFO
    org.hibernate: WARN
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 应用自定义配置
app:
  name: IT技术日报系统
  version: 1.0.0
  description: 抓取国外热门IT技术文章并生成AI日报

# 爬虫配置
crawler:
  schedule:
    enabled: false # 默认禁用定时爬取，避免启动时阻塞
  startup:
    enabled: false # 禁用启动时爬取
  sources:
    hackernews:
      enabled: true
      timeout: 5000 # 连接超时5秒
    github:
      enabled: true
      timeout: 5000
    devto:
      enabled: true
      timeout: 5000

# 阿里云百炼大模型配置
alibaba:
  ai:
    api-key: sk-da3c4b1e330140b8af7490af53e57607
    base-url: https://dashscope.aliyuncs.com
    model:
      translation: qwen-turbo
      summarization: qwen-plus